services:
  - type: web
    name: demo-electric
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: APP_BASE_URL
        value: https://demo-electric.onrender.com/
      - key: DB_DRIVER
        value: Postgre
      - key: DB_PORT
        value: "5432"
      - key: DATABASE_URL
        fromDatabase:
          name: demo-electric-db
          property: connectionString

databases:
  - name: demo-electric-db
    databaseName: demo_electric
    user: demo_electric_user
    plan: free
